#!/bin/sh
# Download the latest version of ISIS to the current directory
rsync -azv --delete --partial isisdist.astrogeology.usgs.gov::x86-64_linux_RHEL6/isis .
rsync -azv --delete --partial isisdist.astrogeology.usgs.gov::isis3data/data/base data/

# Make clean will fail if this autogenerated Makefile is not removed
# make[2]: *** No rule to make target '../../../local/v002/mkspecs/default/qmake.conf', needed by 'Makefile'.  Stop.
# config.mak:41: recipe for target 'clean'
rm isis/config/Makefile
# Remove compiled python bytecode
rm isis/scripts/isis3Startup.pyc
# Remove build artifacts
make --directory=isis -j clean
